#!/bin/bash
for f in *.zip ; do
    echo -n "| [$f" | cut -d "." -f1 | tr -d $'\n' && echo -n "]() | \`" && sha256sum $f | cut -d " " -f1 | tr -d $'\n' && echo -n "\` |";
    if [ -z "$1" ]
    then
	echo "";
    else
	echo " $1 |";
    fi
done
